#\!/bin/bash

echo "🚀 Amplifyx Chatbot - Vercel Setup Script"
echo "=========================================="
echo ""
echo "This script will help you set up the OpenAI API key on Vercel."
echo ""
echo "Prerequisites:"
echo "- Vercel CLI installed (npm i -g vercel)"
echo "- Logged into Vercel (vercel login)"
echo "- OpenAI API key ready"
echo ""
echo "Steps to complete:"
echo ""
echo "1. First, make sure you're in the project directory:"
echo "   cd '/Users/corin/Amplifyx Website'"
echo ""
echo "2. Link this directory to your Vercel project:"
echo "   vercel link"
echo "   (Select the 'amplifyx-chatbot' project)"
echo ""
echo "3. Set your OpenAI API key as an environment variable:"
echo "   vercel env add OPENAI_API_KEY"
echo "   - When prompted, paste your OpenAI API key"
echo "   - Select 'Production', 'Preview', and 'Development'"
echo ""
echo "4. Redeploy to apply the environment variable:"
echo "   vercel --prod"
echo ""
echo "Alternative: Set via Vercel Dashboard"
echo "======================================"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Click on your 'amplifyx-chatbot' project"
echo "3. Go to Settings → Environment Variables"
echo "4. Add a new variable:"
echo "   - Name: OPENAI_API_KEY"
echo "   - Value: [Your OpenAI API key]"
echo "   - Environment: Production, Preview, Development"
echo "5. Click 'Save'"
echo "6. Go to Deployments tab and click 'Redeploy' on the latest deployment"
echo ""
echo "After completing these steps, your chatbot will be fully functional\!"
echo ""
echo "Test it at: https://amplifyx.com.au"
